name: flask-environment
channels:
  - defaults
dependencies:
  - python=3.9
  - flask=2.2.3
  - pandas=1.5.3
  - numpy=1.23.5
  - nltk=3.7
  - scikit-learn=1.2.0
  - joblib=1.2.0
  - pip
  - pip:
      - flask-cors
